### ISSUE TITLE
Getting production deployments in pull requests

### ISSUE THREAD

**Issue by redonkulus** [eliperelman/now-travis#12]
@eliperelman 

Trying out this package, I've noticed that for Pull Requests I get the production and staging status updates. This is problematic as PR changes are now getting pushed to production pre merging.

Here is an example PR:  https://github.com/pure-css/pure-site/pull/390

Here is my travis config:

```yaml
after_script:
  - NOW_ALIAS=purecss.io ./node_modules/.bin/now-travis;
```
or https://github.com/pure-css/pure-site/blob/master/.travis.yml#L8

Am I doing something wrong?

**Comment by redonkulus** [comment]
<img width="775" alt="screen shot 2018-01-20 at 9 05 32 pm" src="https://user-images.githubusercontent.com/193272/35191035-b044e0a4-fe25-11e7-98fb-a5507235e12a.png">

**Comment by jbmoelker** [comment]
@redonkulus I ran into the same issue. I solved it by prepending a bash test to the script:

```yml
after_success:
  - test $TRAVIS_EVENT_TYPE = "pull_request" && now-travis
```

And since I do want aliasing on pushes to master, I added a separate line for that one:

```yml
after_success:
  - test $TRAVIS_EVENT_TYPE = "pull_request" && now-travis
  - test $TRAVIS_EVENT_TYPE = "push" && test $TRAVIS_BRANCH = "master" &&  now-travis && now alias --token=$NOW_TOKEN
```

Note that `now-travis` doesn't do the aliasing in that last line, as I couldn't get that to work. But the Now CLI command works just fine too.

**Comment by swissspidy** [comment]
I now use

```yaml
branches:
  only:
    - master
```

and build stages like this:

```yaml
jobs:
  fast_finish: true
  include:
    # ...

    - stage: deploy
      script:
        - NOW_ALIAS=xyz.now.sh node_modules/.bin/now-travis

stages:
  # ...
  - name: deploy
    if: branch = master
```
